{{- if .Values.configMapData }}
apiVersion: v1
kind: ConfigMap
metadata:
  {{- include "labels.metadata" $ }}
data:
{{- range $key, $value := .Values.configMapData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
