{{- if .Values.secret.enable -}}
{{- $secretFile := .Files.Get .Values.secret.file | fromYaml -}}
{{- if $secretFile }}
apiVersion: v1
kind: Secret
metadata:
  {{- include "labels.metadata" $ }}
type: Opaque
data:
{{- range $key, $value := $secretFile }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}