{{- if .Values.service  }}
# templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  {{- include "labels.metadata" $ }}
  name: {{ .Values.service.name }}
spec:
  selector:
    {{- include "labels" $ | indent 3 }}   # Match this selector with your DeploymentConfig's selector
  ports:
    - protocol: TCP
      name: {{ .Values.service.name }}
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ index .Values.service.nodeport }}   
      {{- end }}
  internalTrafficPolicy: {{ .Values.service.internalTrafficPolicy }} #Cluster/NodePort
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  type: {{ .Values.service.type }} #ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
{{- end }}
